Render Dragons List
shella12/React-group-project pull request #31
Opened 2022-12-21 10:40 UTC by mrsamsharma

- Created a component which has basic list structure for Dragon Item
- Used `useEffect()` to fetch Data from Dragons API
- Used `useSelector()` to store data in API

2022-12-21 13:31 UTC, shella12 requested changes
##
## Hi @mrsamsharma  ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next step of the project. You are almost there!

![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

2022-12-21 13:31 UTC, shella12 commented on src/components/DragonItem.js
> +  /* eslint-enable */
- [ ] I suggest not disabling the linters. Linters ensure you use best practices in programming. Try resolving linter errors manually

2022-12-21 13:31 UTC, shella12 commented on src/components/DragonItem.js
> +        {/* eslint-enable */}
- [ ] I suggest not disabling the linters. Linters ensure you use best practices in programming. Try resolving linter errors manually

2022-12-21 13:31 UTC, shella12 commented on src/redux/Dragon/Dragon.js
> +      img: dragon.flickr_images[0],
Great job @mrsamsharma  🤝

- [ ] There seems to be an error with the way axionr is imported. I think you need to install axion in `Dragon.js`.
![error](https://user-images.githubusercontent.com/44798044/208915001-71f415e1-0855-40f7-a1d6-78a4ae6a78bc.png)

2022-12-22 07:59 UTC, soesandarwin2201 approved these changes
Hi @mrsamsharma , 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/208003070-3834960f-1430-44eb-8b01-560a220447b6.gif)

## Good Highlights✔️
- Linter checks are passing
- Good commit messages
- Adhered to Gitflow



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 08:00 UTC, merged